// Mocks generated by Mockito 5.4.6 from annotations
// in mulligans_law/test/features/members/domain/usecases/get_society_members_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mulligans_law/features/members/domain/entities/member.dart'
    as _i3;
import 'package:mulligans_law/features/members/domain/repositories/member_repository.dart'
    as _i4;
import 'package:mulligans_law/features/societies/domain/entities/society_stats.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSocietyStats_0 extends _i1.SmartFake implements _i2.SocietyStats {
  _FakeSocietyStats_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMember_1 extends _i1.SmartFake implements _i3.Member {
  _FakeMember_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MemberRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemberRepository extends _i1.Mock implements _i4.MemberRepository {
  MockMemberRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.Member>> getSocietyMembers(String? societyId) =>
      (super.noSuchMethod(
            Invocation.method(#getSocietyMembers, [societyId]),
            returnValue: _i5.Future<List<_i3.Member>>.value(<_i3.Member>[]),
          )
          as _i5.Future<List<_i3.Member>>);

  @override
  _i5.Future<int> getMemberCount(String? societyId) =>
      (super.noSuchMethod(
            Invocation.method(#getMemberCount, [societyId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<_i2.SocietyStats> getSocietyStats(String? societyId) =>
      (super.noSuchMethod(
            Invocation.method(#getSocietyStats, [societyId]),
            returnValue: _i5.Future<_i2.SocietyStats>.value(
              _FakeSocietyStats_0(
                this,
                Invocation.method(#getSocietyStats, [societyId]),
              ),
            ),
          )
          as _i5.Future<_i2.SocietyStats>);

  @override
  _i5.Future<_i3.Member> addMember({
    required String? societyId,
    required String? userId,
    required String? name,
    required String? email,
    String? avatarUrl,
    required double? handicap,
    required String? role,
    String? status,
    DateTime? expiresAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addMember, [], {
              #societyId: societyId,
              #userId: userId,
              #name: name,
              #email: email,
              #avatarUrl: avatarUrl,
              #handicap: handicap,
              #role: role,
              #status: status,
              #expiresAt: expiresAt,
            }),
            returnValue: _i5.Future<_i3.Member>.value(
              _FakeMember_1(
                this,
                Invocation.method(#addMember, [], {
                  #societyId: societyId,
                  #userId: userId,
                  #name: name,
                  #email: email,
                  #avatarUrl: avatarUrl,
                  #handicap: handicap,
                  #role: role,
                  #status: status,
                  #expiresAt: expiresAt,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Member>);

  @override
  _i5.Future<_i3.Member> updateMember({
    required String? memberId,
    String? name,
    String? email,
    String? avatarUrl,
    double? handicap,
    String? role,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateMember, [], {
              #memberId: memberId,
              #name: name,
              #email: email,
              #avatarUrl: avatarUrl,
              #handicap: handicap,
              #role: role,
            }),
            returnValue: _i5.Future<_i3.Member>.value(
              _FakeMember_1(
                this,
                Invocation.method(#updateMember, [], {
                  #memberId: memberId,
                  #name: name,
                  #email: email,
                  #avatarUrl: avatarUrl,
                  #handicap: handicap,
                  #role: role,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Member>);

  @override
  _i5.Future<void> removeMember(String? memberId) =>
      (super.noSuchMethod(
            Invocation.method(#removeMember, [memberId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.Member> getMemberById(String? memberId) =>
      (super.noSuchMethod(
            Invocation.method(#getMemberById, [memberId]),
            returnValue: _i5.Future<_i3.Member>.value(
              _FakeMember_1(
                this,
                Invocation.method(#getMemberById, [memberId]),
              ),
            ),
          )
          as _i5.Future<_i3.Member>);

  @override
  _i5.Future<_i3.Member> getPrimaryMember(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getPrimaryMember, [userId]),
            returnValue: _i5.Future<_i3.Member>.value(
              _FakeMember_1(
                this,
                Invocation.method(#getPrimaryMember, [userId]),
              ),
            ),
          )
          as _i5.Future<_i3.Member>);

  @override
  _i5.Future<_i3.Member> createPrimaryMember({
    required String? userId,
    required String? name,
    required String? email,
    required double? handicap,
    String? avatarUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPrimaryMember, [], {
              #userId: userId,
              #name: name,
              #email: email,
              #handicap: handicap,
              #avatarUrl: avatarUrl,
            }),
            returnValue: _i5.Future<_i3.Member>.value(
              _FakeMember_1(
                this,
                Invocation.method(#createPrimaryMember, [], {
                  #userId: userId,
                  #name: name,
                  #email: email,
                  #handicap: handicap,
                  #avatarUrl: avatarUrl,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Member>);

  @override
  _i5.Future<_i3.Member> updatePrimaryMember({
    required String? userId,
    String? name,
    String? email,
    double? handicap,
    String? avatarUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePrimaryMember, [], {
              #userId: userId,
              #name: name,
              #email: email,
              #handicap: handicap,
              #avatarUrl: avatarUrl,
            }),
            returnValue: _i5.Future<_i3.Member>.value(
              _FakeMember_1(
                this,
                Invocation.method(#updatePrimaryMember, [], {
                  #userId: userId,
                  #name: name,
                  #email: email,
                  #handicap: handicap,
                  #avatarUrl: avatarUrl,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Member>);

  @override
  _i5.Future<_i3.Member> updateMemberRole({
    required String? memberId,
    required String? role,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateMemberRole, [], {
              #memberId: memberId,
              #role: role,
            }),
            returnValue: _i5.Future<_i3.Member>.value(
              _FakeMember_1(
                this,
                Invocation.method(#updateMemberRole, [], {
                  #memberId: memberId,
                  #role: role,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Member>);

  @override
  _i5.Future<void> removeSocietyMember(String? memberId) =>
      (super.noSuchMethod(
            Invocation.method(#removeSocietyMember, [memberId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
