# Dependabot configuration for automatic dependency updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Flutter/Dart dependencies (pubspec.yaml)
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "flutter"
      - "dart"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    # Group minor and patch updates together
    groups:
      flutter-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "github-actions"
      - "ci"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"

  # NPM dependencies (Docusaurus)
  - package-ecosystem: "npm"
    directory: "/docs-technical"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "npm"
      - "documentation"
    commit-message:
      prefix: "chore(docs-deps)"
      include: "scope"
    # Ignore major version updates for documentation dependencies
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    # Group all npm updates together
    groups:
      npm-dependencies:
        patterns:
          - "*"
