// Mocks generated by Mockito 5.4.6 from annotations
// in mulligans_law/test/features/auth/domain/usecases/get_current_user_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mulligans_law/features/auth/domain/entities/auth_session.dart'
    as _i2;
import 'package:mulligans_law/features/auth/domain/entities/auth_user.dart'
    as _i3;
import 'package:mulligans_law/features/auth/domain/entities/user_profile.dart'
    as _i6;
import 'package:mulligans_law/features/auth/domain/repositories/auth_repository.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthSession_0 extends _i1.SmartFake implements _i2.AuthSession {
  _FakeAuthSession_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthUser_1 extends _i1.SmartFake implements _i3.AuthUser {
  _FakeAuthUser_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i4.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i3.AuthUser?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i5.Stream<_i3.AuthUser?>.empty(),
          )
          as _i5.Stream<_i3.AuthUser?>);

  @override
  _i5.Future<_i2.AuthSession> signInWithEmail({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmail, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i5.Future<_i2.AuthSession>.value(
              _FakeAuthSession_0(
                this,
                Invocation.method(#signInWithEmail, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.AuthSession>);

  @override
  _i5.Future<_i2.AuthSession> signUpWithEmail({
    required String? email,
    required String? password,
    String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithEmail, [], {
              #email: email,
              #password: password,
              #name: name,
            }),
            returnValue: _i5.Future<_i2.AuthSession>.value(
              _FakeAuthSession_0(
                this,
                Invocation.method(#signUpWithEmail, [], {
                  #email: email,
                  #password: password,
                  #name: name,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.AuthSession>);

  @override
  _i5.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.AuthUser?> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i5.Future<_i3.AuthUser?>.value(),
          )
          as _i5.Future<_i3.AuthUser?>);

  @override
  _i5.Future<_i2.AuthSession?> getCurrentSession() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentSession, []),
            returnValue: _i5.Future<_i2.AuthSession?>.value(),
          )
          as _i5.Future<_i2.AuthSession?>);

  @override
  _i5.Future<void> resetPassword({required String? email}) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {#email: email}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.AuthUser> updateProfile({String? name, String? avatarUrl}) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #name: name,
              #avatarUrl: avatarUrl,
            }),
            returnValue: _i5.Future<_i3.AuthUser>.value(
              _FakeAuthUser_1(
                this,
                Invocation.method(#updateProfile, [], {
                  #name: name,
                  #avatarUrl: avatarUrl,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.AuthUser>);

  @override
  _i5.Future<List<_i6.UserProfile>> searchUsers({
    required String? query,
    int? limit = 20,
    String? excludeSocietyId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsers, [], {
              #query: query,
              #limit: limit,
              #excludeSocietyId: excludeSocietyId,
            }),
            returnValue: _i5.Future<List<_i6.UserProfile>>.value(
              <_i6.UserProfile>[],
            ),
          )
          as _i5.Future<List<_i6.UserProfile>>);
}
